### PR TITLE
Deal with upload of weird/empty/partial files

### PR DESCRIPTION
**Pull request by lodelestra**
## Purpose

Add a notification component to display errors, warnings and infos. Tell users when there is an issue with their sequence files.

Complete description => issue #70 
## Features
- [x] add notifications. Cloned from monod/Notifications
- [x] manage empty file
- [x] manage file without sequence
- [x] manage file with empty header

### CODE REVIEW

**Comment by lodelestra** [comment]
I close every notifications related to file upload when a file is OK. It happens when users upload an empty file, doesn't close the error message and upload a valid one.
To easily filter notifications who need to be closed, I added categories to messages.

**Comment by lodelestra** [comment]
screen shot 2016-10-24 at 16 45 08

**Comment by willdurand** [comment]
👍

**Comment by jmaupetit** [comment]
Thx @lodelestra! Ready for review?

**Comment by lodelestra** [comment]
Ready 😃

**Comment by willdurand** [comment]
Perfect, thanks!

**Pull request merged**
